import fs from 'node:fs/promises';
import { parseTrafficCsv, parseRegistryCsv, buildTargets } from '../targets/build.js';
import { parseTargets } from '../targets/load.js';

/**
 * Regenerates the target list from published data.
 *
 * Takes the two source files as arguments rather than fetching them, so this is
 * a pure transformation that can be re-run against archived inputs to reproduce
 * a past list. Downloading is the workflow's job.
 *
 *   build-targets <traffic.csv> <registry.csv> <overrides.json> <out.json> [limit]
 */
async function main(): Promise<number> {
  const [traffic, registry, overridesPath, out, limitArg] = process.argv.slice(2);
  if (!traffic || !registry || !overridesPath || !out) {
    console.error('usage: build-targets <traffic.csv> <registry.csv> <overrides.json> <out.json> [limit]');
    return 1;
  }

  const limit = Number(limitArg ?? 100);
  if (!Number.isInteger(limit) || limit < 1) {
    console.error(`limit must be a positive integer, got "${limitArg}"`);
    return 1;
  }

  const overrides = JSON.parse(await fs.readFile(overridesPath, 'utf8')) as {
    agencies: Record<string, string>;
  };

  // Read the list being replaced so hosts already measured keep their ids and
  // their history stays joined. A missing or unreadable file is fine — that is
  // simply the first run.
  let existing: Awaited<ReturnType<typeof parseTargets>> = [];
  try {
    existing = parseTargets(await fs.readFile(out, 'utf8'));
  } catch {
    existing = [];
  }

  const result = buildTargets(
    parseTrafficCsv(await fs.readFile(traffic, 'utf8')),
    parseRegistryCsv(await fs.readFile(registry, 'utf8')),
    { limit, overrides: overrides.agencies, existing },
  );

  await fs.writeFile(
    out,
    JSON.stringify(
      {
        _comment:
          'Generated by build-targets from published traffic and registry data. ' +
          'Do not hand-edit: change the sources or the overrides and regenerate. ' +
          'Every entry cites the measurement that earned its place (FR-001a).',
        generated_from: { traffic, registry, limit },
        targets: result.targets,
      },
      null,
      2,
    ) + '\n',
    'utf8',
  );

  // Self-reporting: a verdict, not a transcript. Anything considered and not
  // included is named here rather than vanishing from the count.
  console.log(`considered ${limit} hosts by traffic`);
  console.log(`  included:  ${result.targets.length}`);
  console.log(`  excluded:  ${result.unmatched.length}`);
  for (const u of result.unmatched) console.log(`    - ${u.host}: ${u.reason}`);

  const agencies = new Set(result.targets.map((t) => t.agency));
  console.log(`  agencies:  ${agencies.size}`);
  const kept = result.targets.filter((t) => existing.some((e) => e.host === t.host && e.id === t.id));
  console.log(`  ids kept from the previous list: ${kept.length}/${existing.length}`);
  console.log(`  written:   ${out}`);

  if (result.targets.length === 0) {
    console.error('refusing to publish an empty target list');
    return 1;
  }
  return 0;
}

main()
  .then((code) => {
    process.exitCode = code;
  })
  .catch((error: unknown) => {
    console.error(`cannot build: ${error instanceof Error ? error.message : String(error)}`);
    process.exitCode = 1;
  });
